### ISSUE TITLE
[P2PNet] (FPN) assert num_outs >= self.num_ins - start_level

### ISSUE THREAD

**Issue by yaoqi-zd** [ucas-vg/PointTinyBenchmark#56]
First thanks for the open-source code of your work!

I've set up the python environment and dataset following the README, when I train P2PNet on SeaPerson with the command
```
export GPU=4 && LR=1e-4 && B=2 && WH=(640 640) && CONFIG="TinyPersonV2/p2p/p2p_r50_fpns4_1x_fl_sl1_TinyPersonV2_640" && \
CUDA_VISIBLE_DEVICES=0,1,2,3 PORT=10000 tools/dist_train.sh configs2/${CONFIG}.py $GPU \
--work-dir ../TOV_mmdetection_cache/work_dir/${CONFIG}/trainval${WH[0]}x${WH[1]}_adamlr${LR}_1x_b${B}${GPU}g_coarse/ \
--cfg-options optimizer.lr=${LR} data.samples_per_gpu=${B} \
 data.train.ann_file="data/tiny_set_v2/anns/release/corner/coarse/noise_rg-0-0.25_1/corner_w640_h640/pseuw16h16/rgb_train_w640h640ow100oh100_coarse.json" \
 data.val.ann_file="data/tiny_set_v2/anns/release/rgb_test.json"
```
I get error as below
```
Traceback (most recent call last):
  File "/home/yq223369/.local/lib/python3.7/site-packages/mmcv/utils/registry.py", line 51, in build_from_cfg
    return obj_cls(**args)
  File "/disk2/yaoqi/workspace/Det/PointTinyBenchmark/TOV_mmdetection/mmdet/models/necks/fpn.py", line 96, in __init__
    assert num_outs >= self.num_ins - start_level
AssertionError
```
I look into the configuration file and find the neck and head config as
```
neck=dict(
        type='FPN',
        in_channels=[256, 512, 1024, 2048],
        out_channels=256,
        start_level=0,  # 1     # output only 1 level (cause p2p has no size)
        add_extra_convs='on_input',
        num_outs=1,  # 5
        norm_cfg=norm_cfg,  # add
    ),
    bbox_head=dict(
        norm_cfg=norm_cfg,  # add
        type='P2PHead',
        num_classes=1,
        in_channels=256,
        feat_channels=256,
        stacked_convs=4,  # didi4 TODO: 论文中“three stacked convolutions”
        strides=[4],  # [4, 8, 16, 32, 64] # [8, 16, 32, 64, 128]
        # point_anchor=[(-0.25, -0.25), (0.25, -0.25), (0.25, 0.25), (-0.25, 0.25)],  # Grid
        point_anchor=[(0., 0.)],  # Grid
        loss_cls=dict(
            type='FocalLoss',
            use_sigmoid=True,
            gamma=2.0,
            alpha=0.25,
            loss_weight=1.0
        ),
        loss_reg=dict(type='SmoothL1Loss', beta=1.0 / 9.0, loss_weight=0.5),
        pts_gamma=1,  # γ to 100.
        reg_norm=1,
    ),
```
so I guess you only want to produce single-level feature map from FPN, with stride=4? but the neck config would not pass the assertion above

**Comment by yinglang** [comment]
Very thanks for your feedback. I have update the FPN code that I forget to upload before. 
The problem happended due to the limitation of original FPN's implement of mmdetection. It can not support only output the high resolution level feature.  It is easy to fixed it as [this commit](https://github.com/ucas-vg/PointTinyBenchmark/commit/eb9a5ac5696d03cb3d8182b2d26d19d9f2aabe3d) showing.

**Comment by yaoqi-zd** [comment]
thanks for your reply
