### ISSUE TITLE
[CocoFmtDataset] unexpected keyword argument 'min_gt_size'

### ISSUE THREAD

**Issue by yaoqi-zd** [ucas-vg/PointTinyBenchmark#59]
when I train P2PNet with command
```
export GPU=4 && LR=1e-4 && B=2 && WH=(640 640) && CONFIG="TinyPersonV2/p2p/p2p_r50_fpns4_1x_fl_sl1_TinyPersonV2_640" && \
CUDA_VISIBLE_DEVICES=0,1,2,3 PORT=10000 tools/dist_train.sh configs2/${CONFIG}.py $GPU \
--work-dir ../TOV_mmdetection_cache/work_dir/${CONFIG}/trainval${WH[0]}x${WH[1]}_adamlr${LR}_1x_b${B}${GPU}g_coarse/ \
--cfg-options optimizer.lr=${LR} data.samples_per_gpu=${B} \
 data.train.ann_file="data/tiny_set_v2/anns/release/corner/coarse/noise_rg-0-0.25_1/corner_w640_h640/pseuw16h16/rgb_train_w640h640ow100oh100_coarse.json" \
 data.val.ann_file="data/tiny_set_v2/anns/release/rgb_test.json"
```
I get the following error
```
Traceback (most recent call last):
  File "/home/yq223369/.local/lib/python3.7/site-packages/mmcv/utils/registry.py", line 51, in build_from_cfg
    return obj_cls(**args)
  File "/disk2/yaoqi/workspace/Det/PointTinyBenchmark/TOV_mmdetection/mmdet/datasets/cocofmt.py", line 98, in __init__
    **kwargs
TypeError: __init__() got an unexpected keyword argument 'min_gt_size'
```
Is the CocoFmtDataset out-dated? if I comment the 'min_gt_size' in config file, like the following
```
data = dict(
    samples_per_gpu=1,
    workers_per_gpu=1,
    train=dict(
        # min_gt_size=2,  # add
        type=dataset_type,
        ann_file=data_root + 'anns/release/corner/rgb_train_w640h640ow100oh100.json',
        img_prefix=data_root + 'imgs/',
        pipeline=train_pipeline),
    val=dict(
        type=dataset_type,
        ann_file=data_root + 'anns/release/rgb_valid.json',
        img_prefix=data_root + 'imgs/',
        pipeline=test_pipeline),
    test=dict(
        type=dataset_type,
        ann_file=data_root + 'anns/release/rgb_test.json',
        img_prefix=data_root + 'imgs/',
        pipeline=test_pipeline))
```
I would get the follow error
```
 File "/disk2/yaoqi/workspace/Det/PointTinyBenchmark/TOV_mmdetection/mmdet/models/dense_heads/base_dense_head.py", line 54, in forward_train
    losses = self.loss(*loss_inputs, gt_bboxes_ignore=gt_bboxes_ignore)
  File "/disk2/yaoqi/workspace/Det/PointTinyBenchmark/TOV_mmdetection/mmdet/models/dense_heads/p2p_head.py", line 184, in loss
    assert len(gb) > 0, gt_bboxes
AssertionError: [tensor([[101.8500, 130.5420, 117.8500, 146.5420],
        [239.7760, 117.2900, 255.7760, 133.2900],
        [257.2470, 113.8140, 273.2470, 129.8140],
        [ 36.9550,  43.2810,  52.9550,  59.2810]], device='cuda:2'), tensor([], device='cuda:2', size=(0, 4))]
```
I guess the 'min_gt_size' means each image should have at least 'min_gt_size(here=2)' points?

**Comment by yinglang** [comment]
Code of P2PNet have been updated and have been tested on coco dataset. You can try to have a run : -)

**Comment by yinglang** [comment]
code related to min_gt_size is showing as following:

```py
    def _filter_imgs(self, min_size=32):
        valid_inds = super(CocoFmtDataset, self)._filter_imgs(min_size)

        # filter image only contain ignore_bboxes or too small bbox
        if self.min_gt_size:
            new_valid_inds, valid_img_ids = [], []
            for i, img_id in enumerate(self.img_ids):
                valid = False
                for ann in self.coco.imgToAnns[img_id]:
                    if 'ignore' in ann and ann['ignore']:
                        continue
                    if ann['bbox'][-1] > self.min_gt_size and ann['bbox'][-2] > self.min_gt_size:
                        valid = True
                if valid:
                    new_valid_inds.append(valid_inds[i])
                    valid_img_ids.append(img_id)
            self.img_ids = valid_img_ids
            valid_inds = new_valid_inds

        print("valid image count: ", len(valid_inds))   # add by hui
        return valid_inds
```

when it is set, It will filte out the images(pure-background image) only have ignore bbox or bbox whose size is less than 2.

**Comment by yaoqi-zd** [comment]
I've run P2PNet training successfully on SeaPerson dataset with the latest code, thanks for your help
