### ISSUE TITLE
KeyError: 'BasicLocator is not in the models registry'

### ISSUE THREAD

**Issue by dk-liang** [ucas-vg/PointTinyBenchmark#63]
How to train P2PNet in dota?
when I run python train.py (I set the config as configs2/DOTA/p2p/p2p_r50_fpn_1x_fl_sl1_DOTA_center.py),
it shows:
`
Traceback (most recent call last):
  File "/data/dkliang/projects/synchronous/PointTinyBenchmark-master/TOV_mmdetection/tools/train.py", line 188, in <module>
    main()
  File "/data/dkliang/projects/synchronous/PointTinyBenchmark-master/TOV_mmdetection/tools/train.py", line 161, in main
    test_cfg=cfg.get('test_cfg'))
  File "/home/dkliang/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmdet/models/builder.py", line 59, in build_detector
    cfg, default_args=dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/home/dkliang/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 212, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/dkliang/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/dkliang/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 45, in build_from_cfg
    f'{obj_type} is not in the {registry.name} registry')
KeyError: 'BasicLocator is not in the models registry'

Process finished with exit code 1`

**Comment by yinglang** [comment]
hi, you can have a try as follow:
1) run python tools/train.py or python tools/dist_train.sh in TOV_mmdetection directory instead of TOV_mmdetection/tools
2) put PYTHONPATH=.:$PYTHONPATH before python tools/train.py as 
```sh
PYTHONPATH=.:$PYTHONPATH python tools/train.py
```
